theme: minima 
title: Scatterbrain
description: We are a team dedicated to writing and reviewing literature as well as our own experiences and life. Our blog is a place for open opinions and writing through different angles. 
